# Generated by Django 4.1 on 2022-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='createdon',
            field=models.DateField(auto_now=True),
        ),
    ]
