# Generated by Django 4.0.6 on 2022-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_post_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='default-thumb.jpg', upload_to=''),
        ),
    ]
